app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', function()
{
	return View::make('hello');
});

Route::get('users/login', array('as' => 'users.login', 'uses' => 'UsersController@login'));

Route::any('follows/followme', array('as' => 'follows.followme', 'uses' => 'FollowsController@followme'));

Route::get('users/logindata', array('as' => 'users.logindata', 'uses' => 'UsersController@logindata'));

Route::post('users/loginverify', array('as' => 'users.loginverify', 'uses' => 'UsersController@loginverify'));

Route::get('users/logout', array('as' => 'users.logout', 'uses' => 'UsersController@logout'));

Route::group(array('before' => 'auth'), function() {

	Route::get('synthetweeds/myfeed', array('as' => 'synthetweeds.myfeed', 'uses' => 'SynthetweedsController@myfeed'));

	Route::get('synthetweeds/create', array('as' => 'synthetweeds.create', 'uses' => 'SynthetweedsController@create'));

	Route::get('follows/feed', array('as' => 'follows.feed', 'uses' => 'FollowsController@feed'));

});

Route::resource('users', 'UsersController');

Route::resource('synthetweeds', 'SynthetweedsController', ['only' => ['index','store','whatever', 'destroy', 'update', 'edit', 'show', 'store']]);

Route::resource('follows', 'FollowsController');

app/views/layouts/scaffold.blade.php
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css" rel="stylesheet">
        <script src="//ajax.googleapis.com/ajax/libs/mootools/1.4.5/mootools-yui-compressed.js"></script>
        <style>
            table form { margin-bottom: 0; }
            form ul { margin-left: 0; list-style: none; }
            .error { color: red; font-style: italic; }
            body { padding-top: 20px; }
        </style>
    </head>

    <body>

        <div class="container">
            <div class="row">
                <div class="span12">
                    <div class="navbar">
                        <div class="navbar-inner">
                            <ul class="nav">
                                <li>{{ link_to_route('users.index', 'Synthusers') }}</li>
                                <li>{{ link_to_route('synthetweeds.myfeed', 'Voir mes Tweeds') }}</li>
                                <li>{{ link_to_route('synthetweeds.index', 'Tous les Tweeds') }}</li>
                                <li>{{ link_to_route('follows.feed', 'Flux d\'actu') }}</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            @if (Session::has('message'))
                <div class="flash alert">
                    <p>{{ Session::get('message') }}</p>
                </div>
            @endif

            @yield('main')
        </div>

    </body>

</html>